name: Android Pull Request & Main CI

on:
  #  pull_request:
  #    branches:
  #      - 'main'
  push:
    branches:
      - 'master'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: "Run unit tests, lint and detekt"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: "set up JDK 11"
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: "Setup Gradle Dependencies Cache"
        uses: actions/cache@v3
        with:
          path: |
                  ~/.gradle/caches
                  ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle', '**/*.gradle.kts', '**/gradle-wrapper.properties', 'buildSrc/src/main/java/Versions.kt') }}
      - name: "Run Lint"
        run: ./gradlew lint
      - name: "Run Detekt"
        uses: natiginfo/action-detekt-all@1.22.0-RC1
        with:
          args: --fail-fast --config detekt/detekt.yml
      - name: "Run tests"
        run: ./gradlew testDebugUnitTest
      - name: "Test Summary"
        uses: test-summary/action@v2
        with:
          paths: |
            app/build/test-results/**/TEST-*.xml
        if: always()
